const mongoose = require("mongoose");

const feeStructureSchema = new mongoose.Schema({
  classId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "sclass",
    required: true,
  },
  className: {
    type: String,
    required: true,
  },
  school: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "admin",
    required: true,
  },
  tuitionFee: { type: Number, default: 0 },
  transportFee: { type: Number, default: 0 },
  labFee: { type: Number, default: 0 },
  libraryFee: { type: Number, default: 0 },
  sportsFees: { type: Number, default: 0 },
  computerFee: { type: Number, default: 0 },
  examinationFee: { type: Number, default: 0 },
  admissionFee: { type: Number, default: 0 },
  registrationFee: { type: Number, default: 0 },
  securityDeposit: { type: Number, default: 0 },
  hostelFee: { type: Number, default: 0 },
  stationaryFee: { type: Number, default: 0 },
  uniformFee: { type: Number, default: 0 },
  miscFee: { type: Number, default: 0 },
  assessmentFee: { type: Number, default: 0 },
  securityFee: { type: Number, default: 0 },
  maintenanceFee: { type: Number, default: 0 },
  developmentFee: { type: Number, default: 0 },
  identityCardFee: { type: Number, default: 0 },
  finePenaltyCharges: { type: Number, default: 0 },
  technologyFee: { type: Number, default: 0 },
  medicalFee: { type: Number, default: 0 },
  alumniAssociationFee: { type: Number, default: 0 },
  clubActivityFee: { type: Number, default: 0 },
  culturalEventFee: { type: Number, default: 0 },
  buildingFund: { type: Number, default: 0 },
  graduationFee: { type: Number, default: 0 },
  fieldTripFee: { type: Number, default: 0 },
  mealPlanFee: { type: Number, default: 0 },
  disciplineFee: { type: Number, default: 0 },
  lateSubmissionFee: { type: Number, default: 0 },
  totalFee: { type: Number, default: 0 },
  description: { type: String },
  isActive: { type: Boolean, default: true },
}, { timestamps: true, strict: false, minimize: false });

module.exports = mongoose.model("FeeStructure", feeStructureSchema);
